# Generated by Django 5.0.4 on 2024-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatmessages', models.CharField(max_length=30)),
                ('questions', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Chatbot',
            },
        ),
    ]
