# Generated by Django 5.0.4 on 2024-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='chatmessages',
            field=models.TextField(),
        ),
    ]
